FN :

1.
svm mainly used for the :
complex data seperation
classification problems 
binary classification problems
ex:
spam v/s not spam.etc..


2.
problem with logistic regression:
logistic regression works well when the data is linearlly seperable
but what if the data is complex 
classes  overlap 
decision boundary is not straight 
that is where svm becomes powerfull

* 
Support Vector Machine (SVM) is a Machine Learning algorithm mainly used for:
Classification
Sometimes Regression
max distance is considered as the hyperplain
Kernel Trick is used in non linear vector svm,Kernel transforms data into higher dimensions so separation becomes easier.
mainly used by RBF

Important Terms in SVM:
Hyperplane
Support Vectors
Margin :
hard margin 
soft margin

Advantages of SVM:
High Accuracy
Effective in High Dimensions
Memory Efficient

Limitations of SVM:
Slow for Large Datasets
Hard to Understand
Choosing Kernel is Difficult


===============================================================


y = mx + c
-- m and c values are derived from the data<br>
-- Parameters are values that are learned from data (m&c)<br>
-- Hyperparameters are input parameters which we pass to our models which are not related to data,These are not dependent on data only parameters are dependent on data<br>
-- For each and every algo each input parameters(Hyperparameters) are changed for best result<br>
-- To check which hyperparameters are best fro model we use GridSearchCV and RandomizedSearchCV<br>
-- Difference between GridSearchCV and RandomizedSearchCV is GridSearchCV tries all possible combinations of hyperparameter values.





**** svm for classification ****

In [3]:
# Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

# Load dataset
df = pd.read_csv("Iris.csv")

# Display first 5 rows
print(df.head())

# Remove unnecessary Id column
df = df.drop("Id", axis=1)

# Separate input and output
X = df.drop("Species", axis=1)

y = df["Species"]

# Train test split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Feature Scaling
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

# Create SVM model
svm_classifier = SVC(
    kernel='rbf',
    C=1.0,
    gamma='scale',
    degree = 3,
    probability=True
)

# Train model
svm_classifier.fit(X_train, y_train)

# Prediction
y_pred = svm_classifier.predict(X_test)

# Accuracy
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

# Confusion Matrix
cm = confusion_matrix(y_test, y_pred)

print("Confusion Matrix:")
print(cm)

# Classification Report
print("Classification Report:")
print(classification_report(y_test, y_pred))

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa
Accuracy: 1.0
Confusion Matrix:
[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Classification Report:
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00         9
 Iris-virginica       1.00      1.00      1.00        11

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



# types of kernels in SVM

linear - Linear data

poly - polynomial relationship

rbf - non linear complex data

sigmoid - normal network like behaviour


c = 1 

controls overfitting vs underfitting

small c --> wider margin ---> underfit

large c --> tries to classify all points ---> may overfit

gamma - scale 

controls how far the influence of one data point reaches,

high gamma ---> model memorizes data ---> overfitting

low gamma ---> generalizes better ---> underfitting

============================================================================================================================================================



class sklearn.svm.SVC(*, C=1.0, kernel='rbf', degree=3, gamma='scale', coef0=0.0, shrinking=True, probability=False, tol=0.001, cache_size=200, class_weight=None, verbose=False, max_iter=-1, decision_function_shape='ovr', break_ties=False, random_state=None)


types of hyper parameters 